# Generated by Django 6.0.6 on 2026-06-23 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=255)),
                ('word_difficulty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_word', models.CharField(max_length=255)),
                ('eng_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_translation.englishwords')),
            ],
        ),
        migrations.CreateModel(
            name='UserDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateField()),
                ('eng_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_translation.englishwords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_correct_word', models.IntegerField()),
                ('count_incorrect_word', models.IntegerField()),
                ('last_practiced', models.DateField()),
                ('user_dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_translation.userdictionary')),
            ],
        ),
    ]
